### ISSUE TITLE
Remote-User header not passed from nginx

### ISSUE THREAD

**Issue by fragtastic** [linuxserver/docker-heimdall#101]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Remote-User header should be passed from nginx to php-fpm.

## Current Behavior

Remote-User header is not passed from nginx to php-fpm.

## Steps to Reproduce

1. Pass Remote-User header to Heimdall container
2. Nothing happens

## Environment
**OS:** N/A
**CPU architecture:** all

## Docker logs

There is no error log output as no error or output is triggered.

## Solution
The init script `/etc/cont-init.d/50-config` which modifies `/etc/nginx/fastcgi_params` should contain an entry for adding the line `fastcgi_param REMOTE_USER $http_remote_user;`.

Specifically `\nfastcgi_param  REMOTE_USER $http_remote_user;` to the line.

https://github.com/linuxserver/docker-heimdall/blob/85935bca1a856d57e8a3cd1ed960bac26873dbfb/root/etc/cont-init.d/50-config#L15

**Comment by 4c0d3r** [comment]
freshrss has the same issue.

**Comment by 4c0d3r** [comment]
Couple of thoughts on the security implications.   If either are exposed directly to the web this is not good if nginx passes a remote-user header it receives from an "untrusted source" -- the web.    Folks running swag + authelia, traefik + authelia or keycloak or whatever should be fine provided only swag/traefik/auther proxy is the only container that can access heimdall/freshrss directly.   Freshrss has to have Remote-User support turned on at installation time, and trusted ip addresses configured (127.0.0.1), but heimdall ships with Remote-User support on by default.... maybe make this an environment variable users have to enable in heimdall.    That way, nginx can always pass Remote-User flag but since it's ignored by default, no security issue, and if enabled assume user running a secure proxy?

**Comment by fragtastic** [comment]
I wouldn't expect the container to be directly exposed to the web.
At bare minimum it should be behind a dedicated reverse proxy, such as a main instance of nginx, traefik, etc. in order to properly handle SSL termination and handle passing appropriate headers.

**Comment by fragtastic** [comment]
To be clear, I'm not disagreeing with having something like an environment variable to set on the container to enable/disable Remote-User support.
In this case the application doesn't have an internal option to configure for it. So passing something like `ENABLE_REMOTE_USER=True` which would trigger the addition of the line to the fastcgi params file would be sufficient.

**Comment by 4c0d3r** [comment]
This is still and issue.   Just reinstalled freshrss.

**Comment by 4c0d3r** [comment]
Good fix is adding this to the custom-cont-init.d folder created by the image after first start.   Seems these folders get moved out of the way and recreated on image recreation (lame).

anywho, this works:

as ./custom-cont-init.d/nginx-remote-user.sh
""" 
#!/bin/sh

if [ $(cat /etc/nginx/fastcgi_params | grep 'fastcgi_param  REMOTE_USER $http_remote_user;' | wc -l) == 0 ]; then
   echo -e '\nfastcgi_param  REMOTE_USER $http_remote_user;\n' >> /etc/nginx/fastcgi_params   
fi
"""

**Comment by j0nnymoe** [comment]
> Good fix is adding this to the custom-cont-init.d folder created by the image after first start. Seems these folders get moved out of the way and recreated on image recreation (lame).

Only if the folders/scripts don't have the correct permissions.

**Comment by 4c0d3r** [comment]
and those would be?

**Comment by j0nnymoe** [comment]
The folders will be owned by root and the script inside needs to be owned by root aswell I believe.

**Comment by pagey101** [comment]
Did this ever make it into the image?
